GET https://puhelinluettelo-lry1.onrender.com/api/persons

###
GET https://puhelinluettelo-lry1.onrender.com/info

###
GET https://puhelinluettelo-lry1.onrender.com/api/persons/1

###
GET https://puhelinluettelo-lry1.onrender.com/api/persons/10

###
DELETE https://puhelinluettelo-lry1.onrender.com/api/persons/1

###
DELETE https://puhelinluettelo-lry1.onrender.com/api/persons/10

###
POST https://puhelinluettelo-lry1.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Barney Stinson",
  "number": "09-222234222"
}

###
POST https://puhelinluettelo-lry1.onrender.com/api/persons
Content-Type: application/json

{
  "number": "09-222234222"
}

###
POST https://puhelinluettelo-lry1.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Barney Stinson"
}